CRITICAL - 2021-01-13 00:30:24 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610519424.071, 0.0271, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:30:36 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:30:36 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:31:23 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:31:23 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:31:25 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:31:25 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:31:25 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:31:25 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:31:55 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:31:55 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:32:05 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:32:05 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:41:56 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:41:56 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:41:59 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:41:59 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:42:03 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:42:03 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 00:45:20 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-13 00:45:20 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-13 05:10:07 --> Undefined property: App\Controllers\Auth::$form_validation
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(296): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 296, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->forgot_password()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-13 05:11:24 --> Undefined variable: remember
#0 G:\xampp\htdocs\UBS\pime_somali\app\Views\Auth\index.php(64): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 64, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\View\View.php(246): include('G:\\xampp\\htdocs...')
#2 G:\xampp\htdocs\UBS\pime_somali\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(135): view('auth/index', Array)
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-13 05:19:26 --> Undefined property: App\Controllers\Auth::$form_validation
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(296): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 296, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->forgot_password()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-13 05:29:08 --> xss_clean is not a valid rule.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Validation\Validation.php(333): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('xss_clean')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('login', 'login', 'testing', Array, Array)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(88): CodeIgniter\Controller->validate(Array)
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-13 05:29:48 --> xss_clean is not a valid rule.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Validation\Validation.php(333): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('xss_clean')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('login', 'login', 'testing', Array, Array)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(88): CodeIgniter\Controller->validate(Array)
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-13 05:42:15 --> xss_clean is not a valid rule.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Validation\Validation.php(333): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('xss_clean')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('login', 'login', 'testing', Array, Array)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(89): CodeIgniter\Controller->validate(Array)
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-13 05:43:30 --> Undefined property: App\Controllers\Auth::$security
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(96): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 96, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-13 05:52:41 --> syntax error, unexpected ''remember'' (T_CONSTANT_ENCAPSED_STRING), expecting ']'
#0 G:\xampp\htdocs\UBS\pime_somali\system\Router\Router.php(195): CodeIgniter\Router\Router->autoRoute('/auth/login')
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(793): CodeIgniter\Router\Router->handle('/auth/login')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-13 05:54:02 --> Undefined property: App\Controllers\Auth::$validate
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(85): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 85, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-13 06:27:23 --> Undefined property: Config\tank_auth::$users
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(63): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 63, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('asdfasd', 'fasdfasdfasdf', NULL, true, true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 06:37:52 --> Undefined property: App\Libraries\Tank_auth::$users
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(63): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 63, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('asdfasd', 'fasdfasdfasdf', NULL, true, true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 06:38:52 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::where()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(64): App\Models\Users->get_user_by_login('asdfasd')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('asdfasd', 'fasdfasdfasdf', NULL, true, true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 06:58:34 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::where()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(64): App\Models\Users->get_user_by_login('asdfasd')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('asdfasd', 'fasdfasdfasdf', NULL, true, true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 06:58:58 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::where()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(64): App\Models\Users->get_user_by_login('asdfasd')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('asdfasd', 'fasdfasdfasdf', NULL, true, true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 10:58:25 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::where()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(64): App\Models\Users->get_user_by_login('ghskhfksahk')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 11:01:37 --> Table 'pime_somali.ctbl_users' doesn't exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT *\nFROM `...')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Users.php(172): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(64): App\Models\Users->get_user_by_login('ghskhfksahk')
#6 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#8 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-01-13 11:55:47 --> Undefined property: Config\tank_auth::$config
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(646): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 646, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(138): App\Libraries\Tank_auth->increase_login_attempt('ghskhfksahk')
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-13 12:11:31 --> Undefined property: Config\tank_auth::$config
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(646): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 646, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(138): App\Libraries\Tank_auth->increase_login_attempt('ghskhfksahk')
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-13 12:21:08 --> Trying to get property 'autologin_cookie_name' of non-object
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(590): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'G:\\xampp\\htdocs...', 590, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(41): App\Libraries\Tank_auth->autologin()
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(45): App\Libraries\Tank_auth->__construct()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-13 12:29:18 --> syntax error, unexpected ')'
#0 G:\xampp\htdocs\UBS\pime_somali\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('G:\\xampp\\htdocs...')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Libraries\\T...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Libraries\\T...')
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(45): spl_autoload_call('App\\Libraries\\T...')
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-13 12:34:15 --> Trying to get property 'login_count_attempts' of non-object
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(633): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'G:\\xampp\\htdocs...', 633, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(99): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('ghskhfksahk')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 12:34:50 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(653): App\Models\tank_auth\Login_attempts->increase_attempt('127.0.0.1', 'ghskhfksahk')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(139): App\Libraries\Tank_auth->increase_login_attempt('ghskhfksahk')
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-13 12:36:31 --> Undefined variable: db
#0 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(78): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 78, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(653): App\Models\tank_auth\Login_attempts->increase_attempt('127.0.0.1', 'ghskhfksahk')
#2 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(139): App\Libraries\Tank_auth->increase_login_attempt('ghskhfksahk')
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-13 12:36:56 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(653): App\Models\tank_auth\Login_attempts->increase_attempt('127.0.0.1', 'ghskhfksahk')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(139): App\Libraries\Tank_auth->increase_login_attempt('ghskhfksahk')
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-13 12:43:36 --> Trying to get property 'users' of non-object
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(149): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'G:\\xampp\\htdocs...', 149, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 13:02:18 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(149): App\Models\Users->store_audit(Array, 'ctbl_audit_logo...')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-13 13:04:54 --> Table 'pime_somali.ctbl_audit_logon_errors' doesn't exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\MySQLi\Connection.php(331): mysqli->query('INSERT INTO `ct...')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ct...')
#2 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ct...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ct...', Array, false)
#4 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Users.php(529): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(149): App\Models\Users->store_audit(Array, 'ctbl_audit_logo...')
#6 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(109): App\Libraries\Tank_auth->login('ghskhfksahk', 'aksdfhaksdfaksd', NULL, true, true)
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#8 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-01-13 13:06:47 --> Undefined property: App\Controllers\Auth::$lang
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(119): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 119, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
