CRITICAL - 2021-10-12 16:50:12 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/home', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 16:50:12 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/favicon.ico', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 16:50:16 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/home', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 16:50:16 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/favicon.ico', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 16:50:32 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 16:50:32 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/favicon.ico', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 16:52:01 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/home', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 16:52:02 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/favicon.ico', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 16:55:42 --> Table 'FAWE_db.db_ctbl_users_login_attempts' doesn't exist
#0 C:\xampp\htdocs\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\app\Models\tank_auth\Login_attempts.php(55): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\app\Libraries\Tank_auth.php(707): App\Models\tank_auth\Login_attempts->get_attempts_num('::1', '')
#6 C:\xampp\htdocs\app\Controllers\Auth.php(50): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#7 C:\xampp\htdocs\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#8 C:\xampp\htdocs\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-10-12 16:55:42 --> Table 'FAWE_db.db_ctbl_users_login_attempts' doesn't exist
#0 C:\xampp\htdocs\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\app\Models\tank_auth\Login_attempts.php(55): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\app\Libraries\Tank_auth.php(707): App\Models\tank_auth\Login_attempts->get_attempts_num('::1', '')
#6 C:\xampp\htdocs\app\Controllers\Auth.php(50): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#7 C:\xampp\htdocs\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#8 C:\xampp\htdocs\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-10-12 16:56:12 --> Table 'FAWE_db.db_ctbl_users_login_attempts' doesn't exist
#0 C:\xampp\htdocs\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\app\Models\tank_auth\Login_attempts.php(55): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\app\Libraries\Tank_auth.php(707): App\Models\tank_auth\Login_attempts->get_attempts_num('::1', '')
#6 C:\xampp\htdocs\app\Controllers\Auth.php(50): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#7 C:\xampp\htdocs\system\CodeIgniter.php(918): App\Controllers\Auth->login('')
#8 C:\xampp\htdocs\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-10-12 17:00:14 --> Table 'FAWE_db.db_ctbl_users' doesn't exist
#0 C:\xampp\htdocs\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\app\Models\tank_auth\Users.php(187): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\app\Libraries\Tank_auth.php(72): App\Models\Users->get_user_by_login('daniel123')
#6 C:\xampp\htdocs\app\Controllers\Auth.php(59): App\Libraries\Tank_auth->login('daniel123', 'password', NULL, true, true)
#7 C:\xampp\htdocs\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-10-12 17:04:46 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/home', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-12 17:04:46 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\app\Filters\CheckLogin.php(41): file_get_contents('https://mandemo...')
#2 C:\xampp\htdocs\system\Filters\Filters.php(173): App\Filters\checkLogin->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#3 C:\xampp\htdocs\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/favicon.ico', 'before')
#4 C:\xampp\htdocs\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
